<a href="https://colab.research.google.com/github/gfeyzakorkmaz/Tries/blob/main/NP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np

path = '/content/drive/MyDrive/Dataset/Orders.xlsx'

df = pd.read_excel(path)
df.head()

/usr/local/lib/python3.11/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")


Row Order Priority Order Date  Order  Discount  Unit Price  Order Quantity  \
0    1           High 2017-01-01  28774      0.10           6              32   
1    2  Not Specified 2017-01-01  88028      0.08          96               2   
2    3       Critical 2017-01-02   9285      0.06          41               3   
3    4            Low 2017-01-02  37537      0.00         292               4   
4    5            Low 2017-01-02  37537      0.07         101              43   

     Sales   Profit  Shipping Cost  ...  Customer Customer Name  \
0   172.80   106.36              5  ...      1656   Joy Corbett   
1   176.64    45.64             35  ...      2211    Anita Hahn   
2   115.62    33.90              3  ...       949     Ernest Oh   
3  1168.00   605.08             49  ...        68    Scott Bunn   
4  4038.99  2647.66             45  ...        68    Scott Bunn   

          Region       State          Country / Region           City  \
0        AsiaPac     Central                      Fiji           Suva   
1  North America    Maryland  United States of America          Bowie   
2  North America  California  United States of America    Los Angeles   
3  North America    New York  United States of America  New York City   
4  North America    New York  United States of America  New York City   

   Postal Code            Ship Date       Ship Mode  \
0          NaN  2017-01-02 00:00:00     Regular Air   
1      20715.0  2017-01-03 00:00:00     Express Air   
2      90049.0  2017-01-04 00:00:00     Regular Air   
3      10177.0  2017-01-02 00:00:00  Delivery Truck   
4      10177.0  2017-01-04 00:00:00  Delivery Truck   

                                           SubRegion  
0                                                NaN  
1  East                                          ...  
2  West                                          ...  
3  East                                          ...  
4  East                                          ...  

[5 rows x 26 columns]

In [3]:
sales_array = df['Sales'].to_numpy()
profit_array = df['Profit'].to_numpy()

print(sales_array)
print(profit_array)

[ 172.8   176.64  115.62 ... 3162.2    61.1   123.  ]
[ 106.36   45.64   33.9  ... 1153.6    17.1    21.02]


In [4]:
total_revenue = np.sum(sales_array)
print("Total Revenue:", total_revenue)

Total Revenue: 30069581.97


In [5]:
mean_sales = np.mean(sales_array)
std_sales = np.std(sales_array)
print(f"Mean Sales:, {mean_sales}, Standard Deviation: {std_sales}")

Mean Sales:, 1790.069173115847, Standard Deviation: 4645.127649398903


In [8]:
z_scores = (sales_array - mean_sales) / std_sales
outliers = df[np.abs(z_scores) > 3]
print("Outliers in Sales:", outliers[['Order Date', 'Sales']])

Outliers in Sales:       Order Date     Sales
13    2017-01-03  26766.25
61    2017-01-06  25372.80
79    2017-01-07  44157.33
270   2017-01-22  27628.16
339   2017-01-30  16577.25
...          ...       ...
16638 2020-12-18  16934.26
16732 2020-12-26  26910.72
16740 2020-12-27  28404.00
16766 2020-12-29  24376.32
16780 2020-12-30  52992.00

[335 rows x 2 columns]


In [10]:
min_sales, max_sales = np.min(sales_array), np.max(sales_array)
df['Normalized Sales'] = (sales_array - min_sales) / (max_sales - min_sales)
print(df[['Sales', 'Normalized Sales']].head())

     Sales  Normalized Sales
0   172.80          0.001734
1   176.64          0.001773
2   115.62          0.001157
3  1168.00          0.011774
4  4038.99          0.040736


In [11]:
df['High Discount'] = np.where(df['Discount'] > 0.2, 1, 0)
print(df[['Discount', 'High Discount']].head())

   Discount  High Discount
0      0.10              0
1      0.08              0
2      0.06              0
3      0.00              0
4      0.07              0


In [12]:
df['Profit-to-Sales Ratio'] = np.divide(profit_array, sales_array, out=np.zeros_like(profit_array), where=sales_array!=0)
print(df[['Sales', 'Profit', 'Profit-to-Sales Ratio']].head())

     Sales   Profit  Profit-to-Sales Ratio
0   172.80   106.36               0.615509
1   176.64    45.64               0.258379
2   115.62    33.90               0.293202
3  1168.00   605.08               0.518048
4  4038.99  2647.66               0.655525


In [14]:
df['Cumulative Sales'] = np.cumsum(sales_array)
print(df[['Order Date', 'Cumulative Sales']].head())

  Order Date  Cumulative Sales
0 2017-01-01            172.80
1 2017-01-01            349.44
2 2017-01-02            465.06
3 2017-01-02           1633.06
4 2017-01-02           5672.05


In [15]:
categories = df.groupby('Category')['Profit'].sum().to_numpy()
most_profitable_category = df.groupby('Category')['Profit'].sum().idxmax()
print("Most Profitable Category:", most_profitable_category)

Most Profitable Category: Telephones and Communication


In [16]:
profit_10_percentile = np.percentile(profit_array, 10)
print(f"10th Percentile of Profit: {profit_10_percentile}")

10th Percentile of Profit: 5.520000000000002


In [21]:
loss_orders = df[(profit_array < 0)]
print("Loss-Making Orders:", loss_orders[['Order Date', 'Profit']])

Loss-Making Orders:       Order Date   Profit
29    2017-01-04   -1.560
65    2017-01-06   -3.760
75    2017-01-06   -3.400
77    2017-01-07   -2.900
79    2017-01-07 -736.215
...          ...      ...
16694 2020-12-22   -2.440
16738 2020-12-27  -15.340
16745 2020-12-27  -39.820
16766 2020-12-29 -814.880
16772 2020-12-29 -218.720

[880 rows x 2 columns]


In [22]:
correlation_sales_profit = np.corrcoef(sales_array, profit_array)[0, 1]
print(f"Correlation between Sales and Profit: {correlation_sales_profit}")

Correlation between Sales and Profit: 0.8928091623995417


In [23]:
matrix_representation = np.column_stack((sales_array, profit_array, df['Discount'].to_numpy()))
print("First 5 rows of matrix representation:\n", matrix_representation[:5])

First 5 rows of matrix representation:
 [[1.72800e+02 1.06360e+02 1.00000e-01]
 [1.76640e+02 4.56400e+01 8.00000e-02]
 [1.15620e+02 3.39000e+01 6.00000e-02]
 [1.16800e+03 6.05080e+02 0.00000e+00]
 [4.03899e+03 2.64766e+03 7.00000e-02]]


In [24]:
df['Adjusted Sales'] = np.where(df['Discount'] > 0.3, sales_array * 0.9, sales_array)
print(df[['Sales', 'Discount', 'Adjusted Sales']].head())

     Sales  Discount  Adjusted Sales
0   172.80      0.10          172.80
1   176.64      0.08          176.64
2   115.62      0.06          115.62
3  1168.00      0.00         1168.00
4  4038.99      0.07         4038.99


In [28]:
df['Rolling Average Sales'] = np.convolve(sales_array, np.ones(7)/7, mode='valid')
print(df[['Order Date', 'Rolling Average Sales']].head(10))

ValueError: Length of values (16792) does not match length of index (16798)

In [29]:
df['Rolling Average Sales'] = np.pad(np.convolve(sales_array, np.ones(7)/7, mode='valid'), (3, 3), 'constant', constant_values=np.nan)
#The np.convolve function with mode='valid' returns a shorter array.
#The np.pad function is used here to add 3 elements to the start and 3 to the end of the convolved array,
# making its length match the length of the DataFrame. The added elements are filled with NaN (Not a Number).
print(df[['Order Date', 'Rolling Average Sales']].head(10))

  Order Date  Rolling Average Sales
0 2017-01-01                    NaN
1 2017-01-01                    NaN
2 2017-01-02                    NaN
3 2017-01-02            1502.155714
4 2017-01-02            1562.241429
5 2017-01-02            1542.512857
6 2017-01-02            1694.281429
7 2017-01-02            1532.104286
8 2017-01-02             976.791429
9 2017-01-02             319.722857
